### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by navierula** [bellepixel/constellation#1]
File and Libraries (3/4)
The file imports the libraries necessary for the project. However, in regards to visualizations, it may have been better to use a Jupyter notebook rather than submit a .py file.

Implementation of 2D visualization (3/4)
The 2D grid appears with data plotted on the graph and the visualization; however, there is no indication of custom colors or a title for the graph.

Implementation of 3D visualization (3/4)
The 3D grid appears with the correct data plotted on the graph. The grid is rotatable. However, the graph lacks a title or creative coloring.

**Comment by bellepixel** [comment]
Thank you. I didn't play close enough attention to the rubric at the start and merely followed the instructions. I've incorporated your comments. It is after the deadline but I didn't want you to think your feedback went unnoticed.

**Comment by navierula** [comment]
Thanks for taking the feedback into consideration! :) I hope you continue to make more data visualizations in the future!
